apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-software-templates
  annotations:
    github.com/project-slug: febinmathew707/backstage-software-templates
spec:
  type: other
  lifecycle: unknown
  owner: febinmathew707@gmail.com
